name: Anchore Analyze Container
on:
  workflow_call:
    
jobs:
  Anchore:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Build local container
      uses: docker/build-push-action@v4
      with:
        tags: anchore/image:latest
        push: false
        load: true

    - name: Scan image
      uses: anchore/scan-action@v3
      id: imagescan
      with:
        image: "anchore/image:latest"
        acs-report-enable: true
        fail-build: false