name: Docker SBOM
on:
  workflow_call:

jobs:
  Docker-sbom:
    runs-on: ubuntu-latest
    steps: 
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Build local container
      uses: docker/build-push-action@v4
      with:
        tags: sbom/image:latest
        push: false
        load: true

    - uses: anchore/sbom-action@v0
      with:
        image: sbom/image:latest
